function Spotlight() {
    return(
        <div className="container csa-board text-center">
            <h2> Spotlight </h2>
            <hr />
            <div className="row">
                <p> 
                    During their time at the university, our scholars have developed diverse, unique experiences as they begin their careers. Navigate your own university experience with insight from our scholars on university academics, research, and industry. As always, if you have any questions for our scholars, be sure to <a href="mailto:cscholarsall@ucsd.edu"> send the Chancellor's Scholars' Alliance an email. </a>
                </p>

                <div>
                {/* TEMPLATE
                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> STUDENT_FIRST_NAME STUDENT_LAST_NAME </b> </h4>
                        <p> Cohort </p>
                        <p> <b> MAJOR </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#STUDENT_FIRST_NAME-text"> Read About STUDENT_FIRST_NAME's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "" </p>
                    </div>
                    <div id="STUDENT_FIRST_NAME-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b>  </b></p>
                    <p>  </p>
                    </div>
                </div>  */}
                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="img\spotlight\Rhianen_Callahan.jpeg" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Rhianen Callahan </b> </h4>
                        <p> 2019 Cohort </p>
                        <p> <b> History & Sociocultural Anthropology </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#rhianen-text"> Read About Rhianen's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "The advice I would give to other scholars struggling to find opportunities is don’t lose faith in applying. I have personally struggled with doubting my abilities and feeling like someone else could do the job better than me." </p>
                    </div>
                    <div id="rhianen-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b> What opportunities have you been taken part in since starting at UCSD?  </b></p>
                    <p> Since I became a student at UCSD, I have had the great privilege of being a part of multiple work/research opportunities on campus. My first job was becoming an orientation leader (OL) for Seventh College, which would later inspire me to apply again to be an orientation leader for Marshall this summer. I have also been conducting research for the Anthropology department on meeting the needs of Anthropology students and attracting students from other majors.  </p>
                    <p><b> How did you find this opportunity, and what was the application process like </b></p>
                    <p> I found both opportunities through advertisements. A friend of mine sent me the college OL application and my research position was advertised in the Anthropology department’s newsletter. I had taken a className with the professor in charge, Dr. Saiba Varma. For both opportunities, I was required to send in my resume and later be called in for an interview.  </p>
                    <p><b> What are/were some of your daily tasks?  </b></p>
                    <p> My daily tasks as an OL consisted of hosting a small group of orientees over Zoom. We would go over our designated subject, conduct a bonding activity, I would give a presentation, and then we would have a section for questions at the end. My daily tasks for my research position consist of weekly meetings with my team. We have created a survey together, worked on advertising said survey, and revived the Anthropology club on campus. Currently, we are working on coding the survey results to present to the department and helping anthropology students form their club.  </p>
                    <p><b> Did/Have social distancing guidelines affected any part of your job/research?  </b></p>
                    <p> Both of my positions have been entirely remote. It has been challenging to work without having contact with one another. Many students struggled to participate during orientation, which pushed us OLs to think outside of the box on how to increase socialization.  </p>
                    <p><b> Any advice for other scholars currently struggling to find similar opportunities in your field?  </b></p>
                    <p> The advice I would give to other scholars struggling to find opportunities is don’t lose faith in applying. I have personally struggled with doubting my abilities and feeling like someone else could do the job better than me. I suggest working hard on your interview skills, as the interview process is the main factor in your application. Don’t be afraid to be yourself and to put yourself out there. </p>
                    </div>
                </div>

                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="img\peer-mentoring\2019-2020\Rachel_Luu.jpg" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Rachel Luu </b> </h4>
                        <p> 2018 Cohort </p>
                        <p> <b> Mechanical Engineering </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#rachel-text"> Read About Rachel's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "In both cases of obtaining these opportunities, I made sure to exhibit a great amount of initiative and willingness to learn because both of those qualities lend to being a strong and great researcher." </p>
                    </div>
                    <div id="rachel-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b> What opportunities have you been a part of since starting at UCSD?  </b></p>
                    <p> Since starting at UCSD, I have been able to have the opportunity to explore research with different labs in the engineering department. Last year, I worked in a soft robotics lab at the Center for Medical Devices and currently I am researching with the Meyers Group in the Material Science and Engineering Program within the Mechanical and Aerospace (MAE) Engineering Department.  </p>
                    <p><b> How did you find this opportunity? What was the application process like? </b></p>
                    <p> In my first year, I applied to the GEAR Program run by the IDEA Engineering Student Center, a guided program that introduced engineering students to research on campus. The program had a written application where I wrote extensively about my curiosity to try out research. I was accepted to this program and I was placed in a robotics lab where I was taught the technical basics of conducting research such as how to read papers, write proposals, and make research posters. Overall, participating in the GEAR Program allowed me to build my research skills and prepared me for my later opportunities. For my current position, I signed up for the MAE Mentorship Program and was paired with my graduate student mentor. I got to know my mentor well and he invited me to join his research project because I had a skill set that would be helpful for this particular project. In both cases of obtaining these opportunities, I made sure to exhibit a great amount of initiative and willingness to learn because both of those qualities lend to being a strong and great researcher.  </p>
                    <p><b> What are/were some of your daily tasks?  </b></p>
                    <p> In my current position, I am collaborating on a project with my graduate student mentor where we study keratin based biological structures in order to characterize their mechanical properties. In particular, we study horse hooves as a source for bioinspired design. Some of the tasks I did remotely include reading research papers, modeling the structure of the hoof using computer aided design software, and running finite element analysis simulations on bioinspired models. Additionally, I would meet weekly with my mentor and the research group to report findings and brainstorm research hypotheses. In times when I am able to go in person, I prepare hoof samples to then conduct material compression, tensile, and impact testing using the equipment in the lab.  </p>
                    <p><b> Did/Have social distancing guidelines affected any part of your research?  </b></p>
                    <p> Funny enough, I started my current research project in March 2020 right before COVID regulations took place. Thankfully, the work I was able to do for the project was able to be done remotely since I had the software at home and of course, reading papers could be done anywhere. What helped the remote experience was having scheduled calls with my mentors to stay on track and stay motivated. Unfortunately though, the current situation did inhibit me from being able to get more hands-on experience at first.  </p>
                    <p><b> Any advice for other scholars currently struggling to find similar opportunities in your field?  </b></p>
                    <p> There are many different ways to get into engineering research! You can talk to a Professor, apply for a guided program like GEAR, or apply directly to labs. In my experience, I would recommend you also join mentorship programs or network with graduate students who work on projects that seem interesting to you. Many undergraduates typically work under graduate student researchers so it makes sense to reach out directly to those you would be working with! Nonetheless, please feel free to reach out to me and I am always happy to talk to anyone personally about my work, advice, or engineering research as a whole!  </p>
                    </div>
                </div> 

                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="img\board\sonali_bhanvadia.jpeg" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Sonali Bhanvadia </b> </h4>
                        <p> 2017 Cohort </p>
                        <p> <b> General Biology </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#sonali-text"> Read About Sonali's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "It has been weird starting the program during the pandemic, since the protocols and training has changed a lot (much of it was online until I actually got on my rotations), but the nurses and all of the leadership team were extremely helpful. We have to take caution and wear masks at all times, wash our hands, use hand sanitizer, and wear gloves when advised." </p>
                    </div>
                    <div id="sonali-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b> What opportunities have you been a part of since starting UCSD? </b></p>
                    <p> Research: I’ve volunteered at UCSD School of Medicine since Spring 2019. I am a volunteer research assistant at the Klemke Lab, focusing on cancer research. 

                        Internship: In Spring of 2020, I became a Pathmaker Intern at Palomar Hospital. The Pathmaker Internship Program is a wonderful opportunity for students interested in healthcare and patient care. This specific internship allows interns to part take in direct patient care, from helping patients walk and eat, to assisting nurses and other techs with things like heart monitors, taking vitals, and more. 
                        </p>
                    <p><b> How did you find these opportunities, and what was the application process like for each? </b></p>
                    <p> Research: I found this particular research opportunity on the UCSD Jobs & Internship Facebook page and was able to interview for the position. The application process was fairly easy. All I had to do was email the lab manager about myself and why I believed I would be a good candidate for the position. 

                        Internship: The Pathmaker Internship Program has four rotations, one for each season, that they have applications for on their website. The application is followed by interviews and intensive training. For me, the interview and training was not too bad, but right before I was supposed to start, the pandemic started. 
                        </p>
                    <p><b> Have social distancing guidelines affected any part of your research/internship? </b></p>
                    <p> Research: The position has definitely changed. The lab was shut down in spring when the pandemic first began, but over the summer, my lab was cleared to open and I was able to go in as long as I followed all of the requirements, such as additional training, social distancing, and of course, wearing a mask. Now, in Fall quarter, I have been going more often, but not as often as before the pandemic. I only go if there are specific tasks for me to do, whereas before I was going on a set schedule to observe and shadow as well. 

                        Internship: I was not able to start my position in April as planned. Instead, I started in August. Although I did have the option to defer to later, I knew that they needed a lot of interns, and that many current interns were taking leaves of absence. It has been weird starting the program during the pandemic, since the protocols and training has changed a lot (much of it was online until I actually got on my rotations), but the nurses and all of the leadership team were extremely helpful. We have to take caution and wear masks at all times, wash our hands, use hand sanitizer, and wear gloves when advised. Overall, I really enjoy the program and have been able to perform a lot of direct patient care. It is also very exciting to get to shadow different floors, and learn from all of the different healthcare workers. 
                        </p>
                    <p><b> Any advice for other scholars currently struggling to find opportunities in your field? </b></p>
                    <p> Research: I would recommend emailing professors or checking on REAL Portal, as many volunteers will not be able to return to their previous positions and these have now become available. I would also suggest including in the email or application process that you are aware of the school’s protocols and guidelines regarding the pandemic, as it is vital to stay healthy and keep the environment safe in the given situation. 

                        Internship: I would suggest anyone who is interested in any kind of healthcare to consider applying to the Pathmaker Internship Program, especially since they have applications during different times of the year, and they only require one 4 hour shift every week.
                        </p>
                    </div>
                </div>

                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="img\peer-mentoring\2019-2020\Phillip_Vally.jpg" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Phillip Vally </b> </h4>
                        <p> 2017 Cohort </p>
                        <p> <b> Aerospace Engineering </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#phillip-text"> Read About Phillip's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "Developing new methods to develop new materials, or just finding new materials, better ways of making them cheaper and easily accessible to lots of low-income communities. That's what I want to do." </p>
                    </div>
                    <div id="phillip-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b> What work/internship opportunities have you been a part of since starting UCSD? </b></p>
                    <p>I have taken part in a co-op between General Atomics and UCSD during summer and fall of 2019. I worked on an R&D project for the Magnetic Fusion Energy department within the Energy division. I was responsible for setting up a prototype cryogenic pellet injector. In the summer of 2020, I participated in a remote internship with Lawrence Livermore National Laboratory. I worked on a team with two other interns formulating a conceptual redesign of the Polar Diagnostic Instrument Manipulator, a system that is a part of NIF (National Ignition Facility) at LLNL. </p>
                    <p><b>How did you find these opportunities, and what was the application process like? </b></p>
                    <p>I found these opportunities through company job sites and the Jacobs School of Engineering job portal. The application process involved applying online, initial phone screenings, and in-person interviews.</p>
                    <p><b>Have social distancing guidelines affected any part of your internship? </b></p>
                    <p>My internship at LLNL was converted to a remote one. While I did miss out on coming into the lab and getting hands on experience with hardware, the team at LLNL adapted to the virtual setting and changed the scope of our project. I had an awesome experience where I learned a lot and contributed meaningful work to LLNL. </p>
                    <p> Developing new methods to develop new materials, or just finding new materials, better ways of making them cheaper and easily accessible to lots of low-income communities. That's what I want to do.</p>
                    <p><b>Any advice for other scholars currently struggling to find internships/jobs in your field? </b></p>
                    <p>My biggest advice to my fellow scholars who are trying to land an internship or job is to gain experience outside of the classroom as much as possible. Simply doing well in className is not enough. Join student organizations that are working on cool projects in your field, or pick up an independent project that interests you. With these experiences, you will be able to create a solid resume. Make sure your resume is well structured, consistent in formatting and grammar, and error free. Finally, leverage your network. As they say, it is not what you know, but who you know. Overall, stay diligent and know that success will come to those who work hard. </p>
                    </div>
                </div>

                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                    <img alt="board picture" className="lazy" data-original="img/board/alex_velazquez2.JPG" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Alexis Velazquez Olivera </b> </h4>
                        <p> 2015 Cohort </p>
                        <p> <b>Physics - Materials Specialization </b> </p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#alex-text"> Read About Alex's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                    <p> "It's a little overwhelming, but I know it's what I want to do. That's what's driving me." </p>
                    </div>
                    <div id="alex-text" className="collapse col-sm-12 spotlight-tab-content">
                    <p><b> What kind of research do you do?</b></p>
                    <p>So, I work in different labs on campus, primarily, I focus on doing materials science research. I would say that my main lab is the McKittrick  lab, based in the MAE department. It's a Materials Science lab, but its general theme is focusing on bio-inspired work. Another lab that I have worked in is in the Physics department and that's the Maple lab. Its main focus is producing superconductors that are viable at relatively high temperatures.</p>
                    <p><b>What is your day-to-day work here like as a research assistant?</b></p>
                    <p>It varies depending on the project and the day. I have developed mostly into an independent worker. A lot of research assistants have a lot of hand-holding, which is great, but it leads into being independent like I am. The first basis when you start working in the lab is that you'll first work closely with a graduate student, who is a PhD candidate, rather than the professor themself. Some professors do work with you if it's a smaller lab, but for the most part you work with a graduate student. They'll inform you about the different types of projects that they're working on and ask you what you're more interested in, once you've already gone through those motions with the professor. Once you start working in the lab itself, you'll have to do your safety training first, but then that transitions into doing a little more remedial tasks. It can be something simple like measuring out different masses, doing different calculations, stuff like that, and then just starting simple parts of the project. Eventually, it'll start to develop into where you're a kind of a second leader of the project itself. You'll be making decisions but you'll be checking in with a graduate student still. I personally have gotten to the point where I do help graduate students with their projects, but I also have my own projects that I work on as well. So I have done a lot of the research of my own at this point. I check in with graduate students and professor McKittrick, but for the most part I can make a lot of decisions myself because I have grounded a lot of the work in research as well.</p>
                    <p><b>How did you decide that research was something that you wanted to do?</b></p>
                    <p> I thought about industry at first, if I'm being frank. I realized that the two major options we have are research and industry. I started to think about the fact that I never really gave academia and research a chance. I thought about the fact that, yes, in industry it's an immediate way of making good money [CHUCKLE] but the PhD track pays off a lot more in the long run, at least with respect in certain careers. With a PhD in research, I can actively give back to my community more easily than in industry. So with industry to me I saw it as a place where of course I would be putting in a lot of hours, just like with research, cause they both entail a lot of the same things, and potential make back a lot of money quickly that I could get back in scholarships and things like that. But if I went through the academia track I could integrate myself a lot more in the community while also benefiting myself because of the fact that -- yes in industry I can work with what I like, but in research I would be making what I like.</p>
                    <p> Developing new methods to develop new materials, or just finding new materials, better ways of making them cheaper and easily accessible to lots of low-income communities. That's what I want to do.</p>
                    <p><b>Could you talk about your experience in first reaching out to a lab to talk about doing research there?</b></p>
                    <p>I've had a bit of a non-traditional track. The typical path is that you look up your professors and you email them. And you email them again, because professors are busy. And from there you set up a meeting and start to talk about what you want to do. But I personally am a lot more enthusiastic about it. So what I decided to do was looked up the professors I liked I looked up their teaching schedules, because I know how hard they are to get into contact with via email. So I did email her, but then I decided to enroll in a freshman seminar she was luckily teaching in the same quarter that I found her. And so I attended the seminar and office hours for another className she was teaching and so I got to know her through these experiences very closely before I finally impacted her with the fact that I had been emailing her about research as well. And from there she said "Well, yeah, I already know you, and I knnow you're interested, and I know you're capable, so let me just get you in contact with my graduate students." So from there I had already established a connection with the professor and I started to integrate myself more with the graduate students because they're the ones who can speak to your merit and capability and push the professor to get you more in tune with the lab as well. So that's how I did it. I looked for her in her classes and from there everything just kind of flowed out. But for my other lab, in the Physics department we have a course called PHYS 133, that is literally doing research. So you get placed into a lab, placed in certain projects that they designed in a className. From there I performed well enough that they asked me to come back as a repeating research assistant outside of the className itself. So there's also opportunities like that in other departments, I believe.</p>
                    <p><b>From what I understand, you go to a lot of conferences. What's the build up to going to a conference, to what the conference is like, what do you do there, and then what do you take away from the conference after you get back?</b></p>
                    <p> This is kind of funny because I just finished up a couple of post-conference surveys, so it's kind of fresh on my mind. I would say that the first conference is definitely gonna be an impactful experience. The other conferences somewhat trail off from there, in that they become a kind of normalized activity for you. The first conference is of course the most important, because that's when you first present yourself to the field. A lot of the people at these conferences are going to be repeat-attendees, that in the future might be your colleagues or potential bosses. Whenever you're at a conference, especially your first one, you want to come well-prepared. If you're looking to apply to graduate school, or summer research opportunities or things like that, a lot of people bring business cards, resumes, things like that, because these conferences really seem like giant networking opportunities. I definitely give merit to that, and push that forward a lot, but I also see it as a great opportunity to get feedback on the work you're doing and develop that work. A lot of the time when you attend these, at least as undergrad and even as grad students, you're attending to present your work. There's an opportunity to receive some type of award afterwards. You'll have judges that are the top researchers in your field, most of the time. Those judges will be able to engage with you in on-the-spot conversations about your work. A lot of time they'll be able to give you feedback, because they also do work related to it, so I've also gotten a lot of potential future steps and collaborations offered to me for the work I've been doing. Thankfully, I've had a lot of people ask me to apply to their graduate programs and been given extra support and resources in applying to those graduate programs because of how impressed they were with my work. So it's not only a place where you can network with potential future employers or peers, but it's also a great place to receive a lot of additional resources so you can be successful in your future track. If I'm being honest, it's also a great way to explore and even travel the country.</p>
                    <p> Texas and Indianapolis are the two that I went to this year, and I never would have gone to those places, if I'm being honest, I've always just been like Cali is my life. It was a great experience. Albeit I did not appreciate the weather as much in some areas. That just showed me that I would be willing to live there for a graduate program.</p>
                    <p><b> So do most of these conferences take place at universities with graduate programs?</b></p>
                    <p> They take place at conference halls. So like the San Diego Convention Center, they'd be at places like that. But often times there would be universities, like down the street. At all the conference I've been to, there are different workshops and sessions you can go to, and so these workshops and sessions can teach you about current work that's being done, how to apply to a PhD, and just how to develop yourself as a person in the field. One of the main things I like about them is that they always offer a college tour of the nearest college or colleges. They'll in particular make these college tours gear towards a specific field. So I as a physicist/engineering researcher was able to attend specific workshops and was offered a specific college tour that was different from what my friends in biomaterials and biomedicals experienced. </p>
                    <p><b> For the bulk of the conference, are you standing there science fair style? Or what is it like?</b></p>
                    <p>The main gist of it is, yes, you're presenting your work. Everybody gets to present their work for a range of 2 to 3 hours. But there's so many people cycling through the conference, so it's an ongoing thing. The main attraction for students is the exhibit hall. While you're presenting, in the same room (because it's a giant room) you'll have a lot of graduate schools and people from industry coming and setting up booths with lots of different opportunities. So they can tell you about fee waivers you can only get for attending these conferences, or other fee waivers you can get for low-income needs or stuff like that.</p>
                    <p>Often times they'll ask for your name and they'll get you in their database so they can give you special offers that they provide for people in their database. Most often you're not in it because you're not in the immediate area with that school. It's definitely a great place to get access to a lot more money, if I'm being honest.</p>
                    <p><b>I've heard that you've given a seminar about research?</b></p>
                    <p>I've been asked to give a few talks and a couple lectures as well. Most often times it's just other undergraduate students. For Family Weekend I was asked to present my work with other people who did summer research via the AEP (Academic Enrichment Program) office. While I was presenting the work it wasn't just the students, but their families. So a lot of parents walked up to me and asked me about UCSD as a school and the benefits of research. I found that when I first started doing research my parents said "Oh that's cool, but, where's the money?" That's not how they directly asked it but that's like the whole point of sending us to school, right? Or at least, a major point, for low-income families especially. Some students had told me that they were into it but their parents were not necessarily encouraging. After talking to their parents, explained to them what I was doing and the significance of it -- you know, groundbreaking research -- they were more inclined to support their kids. That was a very good feeling for me. For the most part during these lectures or seminars or small workshops with students, I'm able to give real feedback to the students. When we open it up to more one-on-one conversations or direct questions from the workshop, it gets a lot more real. How are you handling the stress, are you actually eating, do you know if you're going to be doing things like this. I feel like I'm able to give real answers to these students because it's not just -- of course, it's a great opportunity in general, but it does put a strain on your life. Research isn't easy, especially if you're doing great research, but it's definitely a work in progress for everybody. As you work through these things it becomes more second-nature in my opinion.</p>
                    <p><b>How many years have you been doing research now?</b></p>
                    <p> Two? Two and a half. I started not last summer but the summer before that. I had done a high school program with COSMOS. That's a UC-based summer program that gets high school students and gets them to UC campuses so you can see what that experience is like. So we got experience in the lab during that summer, like general lab techniques. But I got close to the professor. So he let me help him, actually, a little with the experiments. So if you get close in any of these types of programs, it would definitely be a benefit. I did a bit of research then, and I helped with some online reading after that, but my first real lab experience didn't come until two summers ago. And from there it's been ongoing.</p>
                    <p><b>So did you start emailing professors, or sign up with a program?</b></p>
                    <p> You can do it either way. Each program varies. Some of these programs you apply to and then they get you in contact with professors affilliated with them. There were a lot of great professors in the programs I applied to, STARS for instance, UCSD STARS, has a list of professors affiliated with them directly. If you apply directly, they'll connect you with a professor you say you want to work with. I had already been working with Professor McKittrick, but she wasn't affiliated with them, so I talked to her and she said she'd be more than interested. A lot of the time professors are crazy about summer undergrads, but they can't get them because you have to pay for them. So it works hand-in-hand in that when you apply to these programs, if you tell them you already have a professor that's interested, that seriously ups the likelihood that you get in, in my opinion. And when you talk to these professors and tell them you have a potential funding source, and you've already established a relationship, it's basically a guaranteed yes. So you benefit by reaching out to both at the same time.</p>
                    <p>If I could go back and do it again, I'd definitely go back and start looking at professors in my first year. Often times people just ask for letters of rec from professors they've had classes with, which is perfectly fine. But if I could go back I would look at all the professors in the department right off the bat and say, "Maybe I should take a className with these professors." Not because their classes are easier, but because I'm actually interested in their work. That way you can integrate yourself into their office hours and classes and start to build that relationship right off the bat. And if you can't take a className with a professor for X, Y, or Z reason, then you can at least start to reach out to them early. When you know you have a professor you like, you can integrate them into your research applications.</p>
                    <p><b>Any last advice for someone trying to get into research, or doesn't know if they want to do it yet?</b></p>
                    <p>If you want to be successful in research, it's definitely a time investment. So, yes, if you're in it for the long run, you have to be really sure in my opinion. But it doesn't hurt to try it out for at least a quarter. I know people that tried out for a lab and were only with them for two weeks. At the end of the day there's no hard feelings. Yes, you are taking some of the lab's resources and it takes time to train you, but even if you only work for a little while they'll still benefit from having you. It doesn't hurt if you're honest. Try it out if it's of any interest of you. But make sure you're constantly reevaluating if it's an experience you like.</p>
                    <p> Research, applying for research opportunities, getting professors interested in you is very much like industry in that you should prepare yourself for rejection. Sometimes it's just that professors don't have funding or time to meet with you. They're also teaching classes, already have undergrad or graduate students to work with, they're mentors in general, and you know, they're people. Even if the professor doesn't respond after two or three emails, it doesn't hurt to be polite and give a week at least or four or five days. Personally, after the third email, I'd be at their office hours. A lot of the time they're not ignoring you, even as an undergraduate student I get almost 200 emails a day. Bear that in mind: it's not you, it's the system.</p>
                    <p><b>What are your plans moving forward?</b></p>
                    <p> I found that I am interested in research, and I'm definitely going to continue considering it. But I'm also interested in industry, still. Apart from my research I've been doing work with project teams, as the project manager. I've been developing a lot of real-world applications for these projects. I'm at the crossroads where it feels like I have to decide right now. So I have applied to a graduate program, but I'm also looking at industry. I'm more than comfortable taking a year to do work. I'm probably going to look for some internship or job for a year. During that time I am still going to be in contact with my professors who have been helping me with my graduate study application, but I've had other external circumstances that make it important for me to get money for my family. But I am still very interested in applying for graduate programs, but that's more long-term. I am okay with waiting a year because I know it's something that I'm passionate about. I know it's not going to deter me from my lifetime goal. I'm trying to do both, I think would be the short answer. It's a little overwhelming, but I know it's what I want to do. That's what's driving me.</p>
                    </div>
                </div>
                
                <div className="spotlight-scholar">
                    <div className="col-sm-4 peer-mentoring-image">
                        <img alt="board picture" className="lazy" data-original="img/peer-mentoring/2018-2019/cindy_ayala.jpg" />
                    </div>
                    <div className="col-sm-3 spotlight-desc">
                        <h4> <b> Cindy Ayala </b> </h4>
                        <p> 2015 Cohort </p>
                        <p> <b> Mechanical Engineering</b></p>
                        <button className="spotlight-btn" data-toggle="collapse" data-target="#cindy-text"> Read About Cindy's Experience </button>
                    </div>
                    <div className="col-sm-5 spotlight-brief">
                        <p> 
                            "I've known that I wanted to work with medical devices for a long time. Being able to work in a research lab that is kind of getting to that -- creating a device you see the in vivo experiments, you feel like you're helping people in the future. That sealed it for me." 
                        </p>
                    </div>
                    <div id="cindy-text" className="collapse col-sm-12 spotlight-tab-content">
                        <hr/>
                        <p><b> What kind of research do you do? </b></p>
                        <p> All of my research has been some type of Bioengineering research. I myself am not a bioengineering major, I guess I've been using my mechanical skills in the bioengineering field. So anything from studying how cells migrate in collagen to developing a device for a dialysis machine. </p>
                        <p><b> How did you decide what type of research you wanted to do?</b></p>
                        <p> I've known that I wanted to work with medical devices for a long time. Being able to work in a research lab that is kind of getting to that -- creating a device you see the in vivo experiments, you feel like you're helping people in the future. That sealed it for me. I knew that I liked the idea of working there. Once I started actually doing the dialysis, I knew for sure that's what I wanted to do. </p>
                        <p><b> What was is your day-to-day experience like? </b></p>
                        <p> During the summer, I would work for 40 hours a week. I would do anything from prepping for experiments, testing materials, and data analysis. During the school year I did 10 hours a week. I would do test prep, preparing cells for experiments, things leading up to experiments, and helping graduate students with their research. </p>
                        <p><b> What advice would you have for someone who is interested in getting into research? </b></p>
                        <p>I would definitely say to at least try to do one research experience, like during the summer. The easiest way that I've seen to go about this is to apply to summer research programs. And it doesn't even have to be at UCSD. There are so many research programs and the top leading research institutions all have these programs specifically to show students what research is all about. I think that's a really great experience to do at least once. I personally did the UC Leads program which is designed for you to apply your second year, but I would encourage first year students to apply for STARS, URC, or other programs that are one summer long. Apart from that, you can always email professors and see if you can get a response. There are three different options from emailing professors: they don't respond at all, which isn't bad and shouldn’t discourage you, or you get a response and they say yeah, let's talk and see if there is a project you could join, or they respond and say, "Hey, I don't have time/funding/etc. right now", but they can guide you to another faculty member who they know can help you. I would say emails help a lot. I got a couple of interviews to work in a different lab through emailing people. It takes a long time and perseverance. A lot of professors don't respond, but sometimes you can get a really good research opportunity. </p>
                        <p><b>  When it comes to emailing professors, especially for underclassmen, a big concern is they don't know what to say, or how to present themselves as someone who is capable of helping do research because I don't feel like I know anything. Do you have any advice for people in that situation? </b></p>
                        <p> I would say do your research on the faculty members. Even if you have no experience, but if you have some type of draw to their research, that helps so you can say "I don't have research experience, but I am very interested in what you're doing." Talk about your main motivation -- not really focused on what you can bring to the group, but how much motivation you have to learn something new. I think that's really important, to say "This is really interesting to me and I'm willing to put the work into it." And, obviously, professors know that most students don’t have prior research experience. They don't expect everyone to come in and know everything. And that's where you have to find a good mentor in the lab either a graduate student or a post-doc, someone who is willing to be like "Hey, I was in your position x number of years ago and want to give a student mentorship like I got." </p>
                        <p><b> How do you go about doing research on professors and what they do? </b></p>
                        <p>Every faculty member has a webpage. They have a little bit of information about their research, and sometimes about the institution that they attended for undergrad, graduate school, and post-doc location. So you can look at their timeline and what their background has been in. You can also google their names in Google Scholar and see their papers. I think that's the easiest way. Just read their papers and see what they're involved in and what direction their research is going. </p>
                        <p><b> How did you get into research? </b></p>
                        <p> At first, I tried just emailing professors in my Freshman year. I also applied for summer research programs. My first research experience was with the Research Experience for Undergraduates (REU) summer program in Bioengineering. They set up everything for me. Based on my goals, they picked a faculty member they thought would be a good fit for me, set up my summer housing, and gave me a summer stipend for food. In that program, I met a graduate student in another lab who needed help in their research, so I was able to jump on that project for the school year. And in my second year, I was accepted into the UC Leads program which funded me for two more years of research.</p>
                        <p><b> What do you mean by being funded? </b></p>
                        <p>Right, so most research programs will fund you which means that, specifically for the summer, they'll pay for your housing, and basically means whatever lab you go to doesn't have to pay you. Funding is usually a big motivator for professors and they are more inclined to let you join their lab if you are funded. It means they don’t have to pay you with their grants and they basically get some “free” labor. If you can begin a conversation with a professor and say "I'm fully funded," it means you're not expecting any money from them to live off of. The lab itself usually pays for the research you're doing in the lab, as in the equipment that you're using and lab supplies, but your own funding for yourself to live off of is through the program.</p>
                        <p><b>If you email people, most of the time, is it going to be a paid position, or are most positions unpaid, or is it more lab-to-lab?</b></p>
                        <p>It's really lab-to-lab. If you're a person who's just starting research, you should come into it expecting that you're not going to get paid but just to learn the basics. I think that's an important point to put when you first send out email. Let the faculty know you're willing to do this as an unpaid internship, just to learn. Some labs do offer paid positions, but I would say you get those after working there for some time or if you have a lot of experience and they really want you to work there. But unpaid positions are still valuable. You're still getting the experience. A lot of times it comes down to the funding of the PI. Some years they have more money from grants than other years which is when you might be offered to be paid. In the end, you could be doing amazing work but the PI might just not have money to pay you that year.</p>
                        <p><b>You mentioned that for summer programs, you would do UC Leads. Are there any other programs like that, or is that the big one?</b></p>
                        <p>UC Leads is a big one because it’s a two-year program. But most other ones are just 8 weeks or 10 weeks. I know UCSD has so many other summer research programs out there. There's SRTP through UCSD, there's the Bioengineering REU, AEP, and there's so many other ones. You can google 'UCSD summer research programs' and they'll be a lot that pop up. The only big thing is that most of those deadlines are pretty early, usually around February, and that would be the main limitation. If someone's in their Spring Quarter and looking for research programs most of them will have already closed.</p>
                        <p><b>What is the typical career path for people who decide to do research?</b></p>
                        <p>In engineering, a lot of people who do graduate school are hoping to do post-doc and then become a PI eventually. But there are others who, after their PhD, will opt for starting a company. I know that a lot of graduate programs even have summer internship opportunities, so you apply to a graduate program and during the summers you go work in industry. So that's what I'm looking towards. To do my research during my PhD, but in the summers have the industry experience.</p>
                        <p><b> What are your personal plans moving forward? </b></p>
                        <p>I'm currently applying to bio-medical engineering programs. I know I don't want to stay in academia in the long run. I would hope to do some type of industry research specifically for medical devices. In grad school, I hope to either work on some type of dialysis machine, like the one I worked on at UCSF, or research in cardiology through computation modeling and fluid dynamics of the heart. One of those two things. And then take that into industry after graduate school.</p>
                        <p><b>Do you have any last pieces of advice or comments about research you mention about research?</b></p>
                        <p>I would just say it's never too early to start, even if you're a first year with little to no experience, you can still start emailing professors. A few faculty members who I emailed my first or second quarter responded saying, "Hi, maybe email me again in a quarter and see how your grades are doing." Keep that connection going. That communication between yourself and the faculty member can really help you in the future.</p>
                        <p>Something I never did but learned later on that really helps is emailing graduate students. They're actually a lot more likely to read their emails than the faculty members and they also know the research that's going on in their labs. So they know if they themselves could use some help or if other grad students in their lab need help. It's a lot more direct and later on you can both talk to the PI together about having you join the lab. And I feel like that is actually a really great way to get into a lab, by talking to grad students first. PIs will usually list their grad students and post-docs on their faculty web page or lab page. You could also search for the first authors of the research papers the PI’s are listed on because a lot of times the graduate students are the first authors of those papers.</p>
                        <p>Overall, it’s never too late and never too early to see if research is for you. You never know unless you try!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Spotlight;